---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- path: content/categories
  label: Categories
  create: all
- path: content
  label: Pages
  create: all
- path: content/post
  label: Posts
  create: all
upload_dir: 100cups100places
public_path: http://res.cloudinary.com/designedbytro/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: 0.42.1
